#pragma once

#ifndef CSP_ADDR
#define CSP_ADDR 15
#endif

#ifndef CSP_ROUTER_TASK_PRIO
#define CSP_ROUTER_TASK_PRIO (configMAX_PRIORITIES - 3)
#endif

#ifndef CSP_ROUTER_STACK_DEPTH
#define CSP_ROUTER_STACK_DEPTH 2048
#endif

#ifndef CSP_PACKETS_DISPATCHER_TASK_PRIO
#define CSP_PACKETS_DISPATCHER_TASK_PRIO (configMAX_PRIORITIES - 4)
#endif

#ifndef CSP_PACKETS_DISPATCHER_STACK_DEPTH
#define CSP_PACKETS_DISPATCHER_STACK_DEPTH 2048
#endif