flags:
    - -mcpu=cortex-m7
    - -mfloat-abi=hard
    - -mfpu=fpv5-d16
    - -mthumb
    - -Wall
    - -O2
    - -g
cflags:
    - -std=gnu99
    - -ffunction-sections
    - -fdata-sections
cxxflags:
    - -std=gnu++20
    - -fno-exceptions
    - -fno-rtti
    - -fno-threadsafe-statics
    - -felide-constructors
    - -fpermissive
    - -Wno-error=narrowing

defines:
    - F_CPU=600000000
    - USB_SERIAL
    - LAYOUT_US_ENGLISH
    - USING_MAKEFILE
    - __IMXRT1062__
    - ARDUINO=10607
    - TEENSYDUINO=159
    - ARDUINO_TEENSY41
    - __NEWLIB__=1
    - ALTERNATIVE_MUTEX_IMPL

library_options:
    libcsp:
        with_max_connections       : 20
        with_conn_queue_length     : 100
        with_router_queue_length   : 100
        with_max_bind_port         : 40
        with_os                    : "freertos"
        with_rtable                : "cidr"
        with_padding               : 2
        enable_crc32               : true
        enable_xtea                : false
        enable_hmac                : false
        enable_dedup               : true
        enable_if_i2c              : false
        enable_if_kiss             : true
        enable_if_can              : false
        enable_rdp                 : false
        disable_stlib              : true
        includes                   : ../../libs/freertos/src